version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
  build:
    commands:
      - VITE_PRODUCTS_API_URL=https://kjgte52mpef3z47rok5fkxiszu0mmlnj.lambda-url.us-east-1.on.aws VITE_ORDERS_API_URL=https://csh5ml7howdgg4ogo5ewsjth3i0hmqys.lambda-url.us-east-1.on.aws npm run build
artifacts:
  base-directory: dist
  files:
    - "**/*"
